### ISSUE TITLE
Maybe Wrong?

### ISSUE THREAD

**Issue by Qsirman** [ajfoggia/KnapsackProblemGA#1]
I have read your code and I am confused what if an invalid chromosome appears? I assume invalid values should be remove or somthing else I don't know. But anyway it should use the variable KNAPSACK_WEIGHT_CAP , which I find is just used for 1 time.

So how can you ensure that invalid chromosomes can be removed or repaired?

**Comment by ajfoggia** [comment]
If an invalid chromosome is created, it is thrown out and recreated. Lines 70-87 handle this exact case where we find out each chromosome's fitness. 

We check if the chromosome is even valid by comparing it against the KNAPSACK_WEIGHT_CAP. If it violates the cap, then we toss it out and create a brand new chromosome. We then check if that new chromosome satisfies the weight cap. If it does, then we can keep that one. Otherwise, we repeat the process of tossing that new one out and creating another new chromosome in its place.
